package asynctest.mapper;

import asynctest.model.KabuAllModel;
import asynctest.model.KabuAllModelExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface KabuAllMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table KABU_ALL_T
     *
     * @mbg.generated Sun Jun 13 02:33:35 JST 2021
     */
    long countByExample(KabuAllModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table KABU_ALL_T
     *
     * @mbg.generated Sun Jun 13 02:33:35 JST 2021
     */
    int deleteByExample(KabuAllModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table KABU_ALL_T
     *
     * @mbg.generated Sun Jun 13 02:33:35 JST 2021
     */
    int deleteByPrimaryKey(@Param("stKabucd") String stKabucd, @Param("stDate") String stDate);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table KABU_ALL_T
     *
     * @mbg.generated Sun Jun 13 02:33:35 JST 2021
     */
    int insert(KabuAllModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table KABU_ALL_T
     *
     * @mbg.generated Sun Jun 13 02:33:35 JST 2021
     */
    int insertSelective(KabuAllModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table KABU_ALL_T
     *
     * @mbg.generated Sun Jun 13 02:33:35 JST 2021
     */
    List<KabuAllModel> selectByExample(KabuAllModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table KABU_ALL_T
     *
     * @mbg.generated Sun Jun 13 02:33:35 JST 2021
     */
    KabuAllModel selectByPrimaryKey(@Param("stKabucd") String stKabucd, @Param("stDate") String stDate);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table KABU_ALL_T
     *
     * @mbg.generated Sun Jun 13 02:33:35 JST 2021
     */
    int updateByExampleSelective(@Param("record") KabuAllModel record, @Param("example") KabuAllModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table KABU_ALL_T
     *
     * @mbg.generated Sun Jun 13 02:33:35 JST 2021
     */
    int updateByExample(@Param("record") KabuAllModel record, @Param("example") KabuAllModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table KABU_ALL_T
     *
     * @mbg.generated Sun Jun 13 02:33:35 JST 2021
     */
    int updateByPrimaryKeySelective(KabuAllModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table KABU_ALL_T
     *
     * @mbg.generated Sun Jun 13 02:33:35 JST 2021
     */
    int updateByPrimaryKey(KabuAllModel record);
}