package asynctest.mapper;

import asynctest.model.MtUserModel;
import asynctest.model.MtUserModelExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface MtUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MT_USER
     *
     * @mbg.generated Sun Jun 13 02:33:35 JST 2021
     */
    long countByExample(MtUserModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MT_USER
     *
     * @mbg.generated Sun Jun 13 02:33:35 JST 2021
     */
    int deleteByExample(MtUserModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MT_USER
     *
     * @mbg.generated Sun Jun 13 02:33:35 JST 2021
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MT_USER
     *
     * @mbg.generated Sun Jun 13 02:33:35 JST 2021
     */
    int insert(MtUserModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MT_USER
     *
     * @mbg.generated Sun Jun 13 02:33:35 JST 2021
     */
    int insertSelective(MtUserModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MT_USER
     *
     * @mbg.generated Sun Jun 13 02:33:35 JST 2021
     */
    List<MtUserModel> selectByExample(MtUserModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MT_USER
     *
     * @mbg.generated Sun Jun 13 02:33:35 JST 2021
     */
    MtUserModel selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MT_USER
     *
     * @mbg.generated Sun Jun 13 02:33:35 JST 2021
     */
    int updateByExampleSelective(@Param("record") MtUserModel record, @Param("example") MtUserModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MT_USER
     *
     * @mbg.generated Sun Jun 13 02:33:35 JST 2021
     */
    int updateByExample(@Param("record") MtUserModel record, @Param("example") MtUserModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MT_USER
     *
     * @mbg.generated Sun Jun 13 02:33:35 JST 2021
     */
    int updateByPrimaryKeySelective(MtUserModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MT_USER
     *
     * @mbg.generated Sun Jun 13 02:33:35 JST 2021
     */
    int updateByPrimaryKey(MtUserModel record);
}