package asynctest.model;

public class KabuAllModel {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column KABU_ALL_T.ST_KABUCD
     *
     * @mbg.generated Sun Jun 13 02:33:35 JST 2021
     */
    private String stKabucd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column KABU_ALL_T.ST_DATE
     *
     * @mbg.generated Sun Jun 13 02:33:35 JST 2021
     */
    private String stDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column KABU_ALL_T.ST_TOUROKUBI
     *
     * @mbg.generated Sun Jun 13 02:33:35 JST 2021
     */
    private String stTourokubi;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column KABU_ALL_T.ST_RONRISAKU_CD
     *
     * @mbg.generated Sun Jun 13 02:33:35 JST 2021
     */
    private String stRonrisakuCd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column KABU_ALL_T.NUM_OPEN
     *
     * @mbg.generated Sun Jun 13 02:33:35 JST 2021
     */
    private Float numOpen;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column KABU_ALL_T.NUM_HIGH
     *
     * @mbg.generated Sun Jun 13 02:33:35 JST 2021
     */
    private Float numHigh;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column KABU_ALL_T.NUM_LOW
     *
     * @mbg.generated Sun Jun 13 02:33:35 JST 2021
     */
    private Float numLow;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column KABU_ALL_T.NUM_CLOSE
     *
     * @mbg.generated Sun Jun 13 02:33:35 JST 2021
     */
    private Float numClose;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column KABU_ALL_T.NUM_DEKIDAKA
     *
     * @mbg.generated Sun Jun 13 02:33:35 JST 2021
     */
    private Float numDekidaka;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column KABU_ALL_T.NUM_SAICHOUSEI
     *
     * @mbg.generated Sun Jun 13 02:33:35 JST 2021
     */
    private Float numSaichousei;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column KABU_ALL_T.NUM_RSI
     *
     * @mbg.generated Sun Jun 13 02:33:35 JST 2021
     */
    private Float numRsi;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column KABU_ALL_T.NUM_RCI
     *
     * @mbg.generated Sun Jun 13 02:33:35 JST 2021
     */
    private Float numRci;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column KABU_ALL_T.NUM_ROC
     *
     * @mbg.generated Sun Jun 13 02:33:35 JST 2021
     */
    private Float numRoc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column KABU_ALL_T.ST_COLFLAG
     *
     * @mbg.generated Sun Jun 13 02:33:35 JST 2021
     */
    private String stColflag;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column KABU_ALL_T.ST_KABUCD
     *
     * @return the value of KABU_ALL_T.ST_KABUCD
     *
     * @mbg.generated Sun Jun 13 02:33:35 JST 2021
     */
    public String getStKabucd() {
        return stKabucd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column KABU_ALL_T.ST_KABUCD
     *
     * @param stKabucd the value for KABU_ALL_T.ST_KABUCD
     *
     * @mbg.generated Sun Jun 13 02:33:35 JST 2021
     */
    public void setStKabucd(String stKabucd) {
        this.stKabucd = stKabucd == null ? null : stKabucd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column KABU_ALL_T.ST_DATE
     *
     * @return the value of KABU_ALL_T.ST_DATE
     *
     * @mbg.generated Sun Jun 13 02:33:35 JST 2021
     */
    public String getStDate() {
        return stDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column KABU_ALL_T.ST_DATE
     *
     * @param stDate the value for KABU_ALL_T.ST_DATE
     *
     * @mbg.generated Sun Jun 13 02:33:35 JST 2021
     */
    public void setStDate(String stDate) {
        this.stDate = stDate == null ? null : stDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column KABU_ALL_T.ST_TOUROKUBI
     *
     * @return the value of KABU_ALL_T.ST_TOUROKUBI
     *
     * @mbg.generated Sun Jun 13 02:33:35 JST 2021
     */
    public String getStTourokubi() {
        return stTourokubi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column KABU_ALL_T.ST_TOUROKUBI
     *
     * @param stTourokubi the value for KABU_ALL_T.ST_TOUROKUBI
     *
     * @mbg.generated Sun Jun 13 02:33:35 JST 2021
     */
    public void setStTourokubi(String stTourokubi) {
        this.stTourokubi = stTourokubi == null ? null : stTourokubi.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column KABU_ALL_T.ST_RONRISAKU_CD
     *
     * @return the value of KABU_ALL_T.ST_RONRISAKU_CD
     *
     * @mbg.generated Sun Jun 13 02:33:35 JST 2021
     */
    public String getStRonrisakuCd() {
        return stRonrisakuCd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column KABU_ALL_T.ST_RONRISAKU_CD
     *
     * @param stRonrisakuCd the value for KABU_ALL_T.ST_RONRISAKU_CD
     *
     * @mbg.generated Sun Jun 13 02:33:35 JST 2021
     */
    public void setStRonrisakuCd(String stRonrisakuCd) {
        this.stRonrisakuCd = stRonrisakuCd == null ? null : stRonrisakuCd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column KABU_ALL_T.NUM_OPEN
     *
     * @return the value of KABU_ALL_T.NUM_OPEN
     *
     * @mbg.generated Sun Jun 13 02:33:35 JST 2021
     */
    public Float getNumOpen() {
        return numOpen;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column KABU_ALL_T.NUM_OPEN
     *
     * @param numOpen the value for KABU_ALL_T.NUM_OPEN
     *
     * @mbg.generated Sun Jun 13 02:33:35 JST 2021
     */
    public void setNumOpen(Float numOpen) {
        this.numOpen = numOpen;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column KABU_ALL_T.NUM_HIGH
     *
     * @return the value of KABU_ALL_T.NUM_HIGH
     *
     * @mbg.generated Sun Jun 13 02:33:35 JST 2021
     */
    public Float getNumHigh() {
        return numHigh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column KABU_ALL_T.NUM_HIGH
     *
     * @param numHigh the value for KABU_ALL_T.NUM_HIGH
     *
     * @mbg.generated Sun Jun 13 02:33:35 JST 2021
     */
    public void setNumHigh(Float numHigh) {
        this.numHigh = numHigh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column KABU_ALL_T.NUM_LOW
     *
     * @return the value of KABU_ALL_T.NUM_LOW
     *
     * @mbg.generated Sun Jun 13 02:33:35 JST 2021
     */
    public Float getNumLow() {
        return numLow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column KABU_ALL_T.NUM_LOW
     *
     * @param numLow the value for KABU_ALL_T.NUM_LOW
     *
     * @mbg.generated Sun Jun 13 02:33:35 JST 2021
     */
    public void setNumLow(Float numLow) {
        this.numLow = numLow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column KABU_ALL_T.NUM_CLOSE
     *
     * @return the value of KABU_ALL_T.NUM_CLOSE
     *
     * @mbg.generated Sun Jun 13 02:33:35 JST 2021
     */
    public Float getNumClose() {
        return numClose;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column KABU_ALL_T.NUM_CLOSE
     *
     * @param numClose the value for KABU_ALL_T.NUM_CLOSE
     *
     * @mbg.generated Sun Jun 13 02:33:35 JST 2021
     */
    public void setNumClose(Float numClose) {
        this.numClose = numClose;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column KABU_ALL_T.NUM_DEKIDAKA
     *
     * @return the value of KABU_ALL_T.NUM_DEKIDAKA
     *
     * @mbg.generated Sun Jun 13 02:33:35 JST 2021
     */
    public Float getNumDekidaka() {
        return numDekidaka;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column KABU_ALL_T.NUM_DEKIDAKA
     *
     * @param numDekidaka the value for KABU_ALL_T.NUM_DEKIDAKA
     *
     * @mbg.generated Sun Jun 13 02:33:35 JST 2021
     */
    public void setNumDekidaka(Float numDekidaka) {
        this.numDekidaka = numDekidaka;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column KABU_ALL_T.NUM_SAICHOUSEI
     *
     * @return the value of KABU_ALL_T.NUM_SAICHOUSEI
     *
     * @mbg.generated Sun Jun 13 02:33:35 JST 2021
     */
    public Float getNumSaichousei() {
        return numSaichousei;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column KABU_ALL_T.NUM_SAICHOUSEI
     *
     * @param numSaichousei the value for KABU_ALL_T.NUM_SAICHOUSEI
     *
     * @mbg.generated Sun Jun 13 02:33:35 JST 2021
     */
    public void setNumSaichousei(Float numSaichousei) {
        this.numSaichousei = numSaichousei;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column KABU_ALL_T.NUM_RSI
     *
     * @return the value of KABU_ALL_T.NUM_RSI
     *
     * @mbg.generated Sun Jun 13 02:33:35 JST 2021
     */
    public Float getNumRsi() {
        return numRsi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column KABU_ALL_T.NUM_RSI
     *
     * @param numRsi the value for KABU_ALL_T.NUM_RSI
     *
     * @mbg.generated Sun Jun 13 02:33:35 JST 2021
     */
    public void setNumRsi(Float numRsi) {
        this.numRsi = numRsi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column KABU_ALL_T.NUM_RCI
     *
     * @return the value of KABU_ALL_T.NUM_RCI
     *
     * @mbg.generated Sun Jun 13 02:33:35 JST 2021
     */
    public Float getNumRci() {
        return numRci;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column KABU_ALL_T.NUM_RCI
     *
     * @param numRci the value for KABU_ALL_T.NUM_RCI
     *
     * @mbg.generated Sun Jun 13 02:33:35 JST 2021
     */
    public void setNumRci(Float numRci) {
        this.numRci = numRci;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column KABU_ALL_T.NUM_ROC
     *
     * @return the value of KABU_ALL_T.NUM_ROC
     *
     * @mbg.generated Sun Jun 13 02:33:35 JST 2021
     */
    public Float getNumRoc() {
        return numRoc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column KABU_ALL_T.NUM_ROC
     *
     * @param numRoc the value for KABU_ALL_T.NUM_ROC
     *
     * @mbg.generated Sun Jun 13 02:33:35 JST 2021
     */
    public void setNumRoc(Float numRoc) {
        this.numRoc = numRoc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column KABU_ALL_T.ST_COLFLAG
     *
     * @return the value of KABU_ALL_T.ST_COLFLAG
     *
     * @mbg.generated Sun Jun 13 02:33:35 JST 2021
     */
    public String getStColflag() {
        return stColflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column KABU_ALL_T.ST_COLFLAG
     *
     * @param stColflag the value for KABU_ALL_T.ST_COLFLAG
     *
     * @mbg.generated Sun Jun 13 02:33:35 JST 2021
     */
    public void setStColflag(String stColflag) {
        this.stColflag = stColflag == null ? null : stColflag.trim();
    }
}