package asynctest.model;

import java.util.Date;

public class MtUserModel {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MT_USER.ID
     *
     * @mbg.generated Sun Jun 13 02:33:35 JST 2021
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MT_USER.NAME
     *
     * @mbg.generated Sun Jun 13 02:33:35 JST 2021
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MT_USER.NAME_KANA
     *
     * @mbg.generated Sun Jun 13 02:33:35 JST 2021
     */
    private String nameKana;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MT_USER.PASS
     *
     * @mbg.generated Sun Jun 13 02:33:35 JST 2021
     */
    private String pass;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MT_USER.MAIL
     *
     * @mbg.generated Sun Jun 13 02:33:35 JST 2021
     */
    private String mail;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MT_USER.JOB
     *
     * @mbg.generated Sun Jun 13 02:33:35 JST 2021
     */
    private String job;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MT_USER.PERMISSION
     *
     * @mbg.generated Sun Jun 13 02:33:35 JST 2021
     */
    private String permission;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MT_USER.ValidFlag
     *
     * @mbg.generated Sun Jun 13 02:33:35 JST 2021
     */
    private String validflag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MT_USER.CREATEDATE
     *
     * @mbg.generated Sun Jun 13 02:33:35 JST 2021
     */
    private Date createdate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MT_USER.UPDATEDATE
     *
     * @mbg.generated Sun Jun 13 02:33:35 JST 2021
     */
    private Date updatedate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MT_USER.ID
     *
     * @return the value of MT_USER.ID
     *
     * @mbg.generated Sun Jun 13 02:33:35 JST 2021
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MT_USER.ID
     *
     * @param id the value for MT_USER.ID
     *
     * @mbg.generated Sun Jun 13 02:33:35 JST 2021
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MT_USER.NAME
     *
     * @return the value of MT_USER.NAME
     *
     * @mbg.generated Sun Jun 13 02:33:35 JST 2021
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MT_USER.NAME
     *
     * @param name the value for MT_USER.NAME
     *
     * @mbg.generated Sun Jun 13 02:33:35 JST 2021
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MT_USER.NAME_KANA
     *
     * @return the value of MT_USER.NAME_KANA
     *
     * @mbg.generated Sun Jun 13 02:33:35 JST 2021
     */
    public String getNameKana() {
        return nameKana;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MT_USER.NAME_KANA
     *
     * @param nameKana the value for MT_USER.NAME_KANA
     *
     * @mbg.generated Sun Jun 13 02:33:35 JST 2021
     */
    public void setNameKana(String nameKana) {
        this.nameKana = nameKana == null ? null : nameKana.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MT_USER.PASS
     *
     * @return the value of MT_USER.PASS
     *
     * @mbg.generated Sun Jun 13 02:33:35 JST 2021
     */
    public String getPass() {
        return pass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MT_USER.PASS
     *
     * @param pass the value for MT_USER.PASS
     *
     * @mbg.generated Sun Jun 13 02:33:35 JST 2021
     */
    public void setPass(String pass) {
        this.pass = pass == null ? null : pass.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MT_USER.MAIL
     *
     * @return the value of MT_USER.MAIL
     *
     * @mbg.generated Sun Jun 13 02:33:35 JST 2021
     */
    public String getMail() {
        return mail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MT_USER.MAIL
     *
     * @param mail the value for MT_USER.MAIL
     *
     * @mbg.generated Sun Jun 13 02:33:35 JST 2021
     */
    public void setMail(String mail) {
        this.mail = mail == null ? null : mail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MT_USER.JOB
     *
     * @return the value of MT_USER.JOB
     *
     * @mbg.generated Sun Jun 13 02:33:35 JST 2021
     */
    public String getJob() {
        return job;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MT_USER.JOB
     *
     * @param job the value for MT_USER.JOB
     *
     * @mbg.generated Sun Jun 13 02:33:35 JST 2021
     */
    public void setJob(String job) {
        this.job = job == null ? null : job.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MT_USER.PERMISSION
     *
     * @return the value of MT_USER.PERMISSION
     *
     * @mbg.generated Sun Jun 13 02:33:35 JST 2021
     */
    public String getPermission() {
        return permission;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MT_USER.PERMISSION
     *
     * @param permission the value for MT_USER.PERMISSION
     *
     * @mbg.generated Sun Jun 13 02:33:35 JST 2021
     */
    public void setPermission(String permission) {
        this.permission = permission == null ? null : permission.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MT_USER.ValidFlag
     *
     * @return the value of MT_USER.ValidFlag
     *
     * @mbg.generated Sun Jun 13 02:33:35 JST 2021
     */
    public String getValidflag() {
        return validflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MT_USER.ValidFlag
     *
     * @param validflag the value for MT_USER.ValidFlag
     *
     * @mbg.generated Sun Jun 13 02:33:35 JST 2021
     */
    public void setValidflag(String validflag) {
        this.validflag = validflag == null ? null : validflag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MT_USER.CREATEDATE
     *
     * @return the value of MT_USER.CREATEDATE
     *
     * @mbg.generated Sun Jun 13 02:33:35 JST 2021
     */
    public Date getCreatedate() {
        return createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MT_USER.CREATEDATE
     *
     * @param createdate the value for MT_USER.CREATEDATE
     *
     * @mbg.generated Sun Jun 13 02:33:35 JST 2021
     */
    public void setCreatedate(Date createdate) {
        this.createdate = createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MT_USER.UPDATEDATE
     *
     * @return the value of MT_USER.UPDATEDATE
     *
     * @mbg.generated Sun Jun 13 02:33:35 JST 2021
     */
    public Date getUpdatedate() {
        return updatedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MT_USER.UPDATEDATE
     *
     * @param updatedate the value for MT_USER.UPDATEDATE
     *
     * @mbg.generated Sun Jun 13 02:33:35 JST 2021
     */
    public void setUpdatedate(Date updatedate) {
        this.updatedate = updatedate;
    }
}